
    [hmeng@localhost runc]$ uname -a
    Linux localhost.localdomain 3.10.0-327.18.2.el7.x86_64 #1 SMP Fri Apr 8 05:09:53 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
    
    [hmeng@localhost runc]$ cat /etc/redhat-release 
    Red Hat Enterprise Linux Server release 7.2 (Maipo)
    
    [hmeng@localhost runc]$ go version
    go version go1.6.2 linux/amd64
    
    [hmeng@localhost runc]$ pwd
    /home/hmeng/go/src/github.com/opencontainers/runc
    [meng@localhost runc]$ git branch
    * 901
      master
    [hmeng@localhost runc]$ git log
    commit bb5473fb5358bca2f4df0ff5c3a8e66ebaaecfdf
    Author: Mrunal Patel <mrunalp@gmail.com>
    Date:   Thu Jun 9 15:58:50 2016 -0700
    
        integration: Fix race in TestFreeze


   
There are 5 failures in the unit test:

    === RUN   TestUsernsExecPS
    time="2016-06-10T17:35:03Z" level=warning msg="os: process already finished" 
    --- FAIL: TestUsernsExecPS (0.05s)
    	exec_test.go:49: nsenter: Unable to unshare namespaces: Invalid argument
    		nsenter: Unable to fork: Invalid argument
    		|: process_linux.go:241: running exec setns process for init caused "exit status 1"
    
    === RUN   TestUsernsRlimit
    time="2016-06-10T17:35:04Z" level=warning msg="os: process already finished" 
    --- FAIL: TestUsernsRlimit (0.02s)
    	utils_test.go:48: exec_test.go:197: unexpected error: process_linux.go:241: running exec setns process for init caused "exit status 1"
    	
    --- FAIL: TestInitJoinNetworkAndUser (0.01s)
    	utils_test.go:48: exec_test.go:1578: unexpected error: process_linux.go:241: running exec setns process for init caused "exit status 1"
    
    === RUN   TestExecInUsernsRlimit
    time="2016-06-10T17:35:12Z" level=warning msg="os: process already finished" 
    --- FAIL: TestExecInUsernsRlimit (0.01s)
    	utils_test.go:48: execin_test.go:109: unexpected error: process_linux.go:241: running exec setns process for init caused "exit status 1"
    
    === RUN   TestExecInUserns
    time="2016-06-10T17:35:14Z" level=warning msg="os: process already finished" 
    --- FAIL: TestExecInUserns (0.01s)
    	utils_test.go:48: execin_test.go:462: unexpected error: process_linux.go:241: running exec setns process for init caused "exit status 1"
	

	
test 15 in bats failed:

    not ok 15 runc exec
    # (in test file tests/integration/exec.bats, line 24)
    #   `[[ "${output}" == *"Hello from exec"* ]]' failed
    # text echoed = ''

